---
- name: Create app container
  docker_container:
    name: "{{application_name}}"
    image: "namelivia/{{application_name}}:latest"
    memory: "200MB"
    pull: true
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
        awslogs-region: "{{cloudwatch_region}}"
        awslogs-group: "{{cloudwatch_log_group}}"
        awslogs-stream: "{{application_name}}"
    networks:
      - name: "pomerium"
    exposed_ports:
      - "80"
    env:
      DATABASE_URL: "{{database_url}}"
      JWK_ENDPOINT: "{{jwk_endpoint}}"

- include_role:
    name: namelivia.postgres
    tasks_from: create-postgres-database-if-not-exists

- include_role:
    name: namelivia.fastapi
    tasks_from: upgrade-alembic

- include_role:
    name: namelivia.backups
    tasks_from: setup-postgres-database-backups

- include_role:
    name: namelivia.backups
    tasks_from: setup-s3-backups
